name: protein-structure-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - biopython
  - pyyaml
  - tqdm
  - pytest
  - matplotlib
  - pip
  - pip:
      - mmcif-pdbx
